### ISSUE TITLE
[Aztec + GB] text-columns block adds a paragraph tag in between

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/AztecEditor-Android#686] opened 2018-05-28 19:30 UTC
### Expected
Using a `<!-- wp:text-columns -->` Gutenberg block on Aztec shouldn't modify it.

### Observed
When writing a post that has a GB block in it with this original code:

```
<!-- wp:text-columns -->
<div class="wp-block-text-columns alignundefined columns-2">
	<div class="wp-block-column">
		<p>one column<br/>second row</p>
	</div>
	<div class="wp-block-column">
		<p>second column<br/>second row col2</p>
	</div>
</div>
<!-- /wp:text-columns -->
```

Opening such a Post in Aztec makes it change to:

```
<!-- wp:text-columns -->
<div class="wp-block-text-columns alignundefined columns-2">
	<div class="wp-block-column">
		<p>one column<br>second row</p>
	</div>
	<p></p>
	<div class="wp-block-column">
		<p>second column<br>second row col2</p>
	</div>
</div>
<!-- /wp:text-columns -->
```

### Reproduced
1. write an empty draft on Gutenberg and insert a new `text-columns` block  with 2 columns and 2 rows, or switch to HTML mode and  include the following:

```
<!-- wp:text-columns -->
<div class="wp-block-text-columns alignundefined columns-2">
	<div class="wp-block-column">
		<p>one column<br>second row</p>
	</div>
	<div class="wp-block-column">
		<p>second column<br>second row col2</p>
	</div>
</div>
<!-- /wp:text-columns -->
```
2. Save and open in Aztec
3. Observe the converted code has now a `<p></p>` in it:

```
<!-- wp:text-columns -->
<div class="wp-block-text-columns alignundefined columns-2">
	<div class="wp-block-column">
		<p>one column<br>second row</p>
	</div>
	<p></p>
	<div class="wp-block-column">
		<p>second column<br>second row col2</p>
	</div>
</div>
<!-- /wp:text-columns -->
```

Note: tested both Calypso mode on/off, same results

#### Tested
[Google Pixel] on [8.0] with [1.3.4]

**Comment by daniloercoli** [comment] 2018-05-30 12:56
Actually this issue is not limited to GB blocks, but happening also on "standard" HTML document like the following:
```
<div>
 <p>first paragraph</p>
</div>
<p>second par</p>
```

`p` tags are inserted in the middle when you switch between HTML and visual mode, resulting in something like this:
```
<div>
 <p>first paragraph</p>
</div>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<p>second par</p>
```

Should we remove the GB label and change the title?

**Comment by mzorz** [comment] 2018-05-30 13:21
Good catch @daniloercoli  - please let's open a new issue with this finding, and link to this one, so we can keep track  / context of how the finding came to be and that by fixing the real issue we fix the GB issue as well.

**Comment by hypest** [comment] 2018-06-08 17:50
Can't reproduce anymore. I think it got fixed with https://github.com/wordpress-mobile/AztecEditor-Android/pull/697.

**Closed by hypest** 2018-06-08 17:50 UTC
Labels: Gutenberg
