### ISSUE TITLE
Button for Adding Media not Working

### ISSUE THREAD

**Issue by ChrissiePollock** [wordpress-mobile/AztecEditor-Android#471] opened 2017-08-29 16:22 UTC
### Expected

User should be able to tap either "Take photo," "Take Video," "Choose photo from device," or "Choose video from device" to upload media to their library.

### Observed

The buttons are not highlighted and will not allow the user to select.

![screen shot 2017-08-29 at 12 21 19 pm](https://user-images.githubusercontent.com/2545184/29831921-a2fe9f76-8cb4-11e7-863a-135ee293f1b0.png)

### Reproduced

Confirmed bug according to Sérgio. 

#### Tested

WordPress - 8.0 - Version code: 448 
Android device name: LGE LG-H818 

Internal report: #216307-h

**Comment by theck13** [comment] 2017-08-29 16:25
This is a duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/6595.  The issue has been [merged](https://github.com/wordpress-mobile/WordPress-Android/pull/6596) into `release/8.2` and will be including in the next release.

**Closed by theck13** 2017-08-29 16:25 UTC

**Comment by mzorz** [comment] 2017-08-29 16:28
Just FYI - I'm cherry-picking this one to get into 8.1 before full rollout 👍 (just waiting for some other last-minute fixes to come in first)

**Comment by prasad456** [comment] 2019-08-04 04:31
@theck13  for latest relaese also show media options button hide other tools but not displaying any media options
