### ISSUE TITLE
Copy/Pasting Lists Crashes the App

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/AztecEditor-Android#441] opened 2017-07-31 12:22 UTC
Originally reported by @rachelmcr:

An Android user reported a crash while copying and pasting content in Aztec, in particular a list. I can reproduce the crash with these steps:

1. Create a post with a list in it.
2. Copy the list.
3. Paste the list at the end of the post. Result: The list is added but list formatting is lost. (Small bug.)
4. Move the cursor to another part of the post and paste the list again. Result: The app crashes.

I tested with other kinds of formatting (e.g. blockquotes, links) but so far only reproduced it with lists.

**Comment by 0nko** [comment] 2017-08-03 14:53
This is a duplicate of #424.

**Closed by 0nko** 2017-08-03 14:53 UTC
Labels: bug, high priority
