### ISSUE TITLE
History: Retain cursor position with history item

### ISSUE THREAD

**Issue by AmandaRiu** [wordpress-mobile/AztecEditor-Android#563] opened 2017-12-05 16:34 UTC
### Expected
Undo/Redo actions should restore cursor position at that moment in time. 

### Observed
After applying redo/undo, the cursor either disappears or is off at some unexpected position. Perhaps its position could be recorded along with the HTML content. 

### Reproduce
1. Add some text. 
2. Delete a word in the middle. 
3. Hit undo. 
4. Note the position of the cursor (or lack thereof)

## Tested
Emulator Nexus 5x API 26

#552 - Initially commented

**Comment by maxme** [comment] 2017-12-06 14:25
This is a duplicate of https://github.com/wordpress-mobile/AztecEditor-Android/issues/341

**Closed by maxme** 2017-12-06 14:25 UTC
Labels: duplicate, enhancement, low priority
