### ISSUE TITLE
Format Buttons Don't Work When Selecting Text Backwards with Keyboard

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/AztecEditor-Android#359] opened 2017-06-06 23:06 UTC
### Expected
Tapping any format button will apply/remove the associated format to selected text.

### Observed
Tapping certain format buttons will not apply/remove the associated format when selecting text backwards with keyboard.  The following formats and actions are affected.

Format|Action(s)
-|-
|Paragraph|Apply|
|Bold|Apply / Remove|
|Italic|Apply / Remove|
|Strikethrough|Apply / Remove|
|Underline|Apply / Remove|
|Quote|Remove|
|List (Ordered)|Remove|
|List (Unordered)|Remove|

### Reproduced
***Paragraph***
1. Enter "this" text.
2. Place cursor after "s" in "this" text.
3. Hold ***Shift*** key and tap ***Left Arrow*** key four times.
4. Tap ***Heading*** format button.
5. Tap ***Heading 1*** option.
6. Tap ***Heading*** format button.
7. Tap ***Paragraph*** option.
8. Notice ***Paragraph*** format option is active, but text format is not applied.

***Bold***
1. Enter "this" text.
2. Place cursor after "s" in "this" text.
3. Hold ***Shift*** key and tap ***Left Arrow*** key four times.
4. Tap ***Bold*** format button.
5. Notice ***Bold*** format button is active, but text format is not applied.
6. Place cursor before "t" in "this" text.
7. Hold ***Shift*** key and tap ***Right Arrow*** key four times.
8. Tap ***Bold*** format button.
9. Place cursor after "s" in "this" text.
10. Hold ***Shift*** key and tap ***Left Arrow*** key four times.
11. Tap ***Bold*** format button.
12. Notice ***Bold*** format button is inactive, but text format is not removed.

***Italic***
1. Enter "this" text.
2. Place cursor after "s" in "this" text.
3. Hold ***Shift*** key and tap ***Left Arrow*** key four times.
4. Tap ***Italic*** format button.
5. Notice ***Italic*** format button is active, but text format is not applied.
6. Place cursor before "t" in "this" text.
7. Hold ***Shift*** key and tap ***Right Arrow*** key four times.
8. Tap ***Italic*** format button.
9. Place cursor after "s" in "this" text.
10. Hold ***Shift*** key and tap ***Left Arrow*** key four times.
11. Tap ***Italic*** format button.
12. Notice ***Italic*** format button is inactive, but text format is not removed.

***Strikethrough***
1. Enter "this" text.
2. Place cursor after "s" in "this" text.
3. Hold ***Shift*** key and tap ***Left Arrow*** key four times.
4. Tap ***Strikethrough*** format button.
5. Notice ***Strikethrough*** format button is active, but text format is not applied.
6. Place cursor before "t" in "this" text.
7. Hold ***Shift*** key and tap ***Right Arrow*** key four times.
8. Tap ***Strikethrough*** format button.
9. Place cursor after "s" in "this" text.
10. Hold ***Shift*** key and tap ***Left Arrow*** key four times.
11. Tap ***Strikethrough*** format button.
12. Notice ***Strikethrough*** format button is inactive, but text format is not removed.

***Underline***
1. Enter "this" text.
2. Place cursor after "s" in "this" text.
3. Hold ***Shift*** key and tap ***Left Arrow*** key four times.
4. Tap ***Underline*** format button.
5. Notice ***Underline*** format button is active, but text format is not applied.
6. Place cursor before "t" in "this" text.
7. Hold ***Shift*** key and tap ***Right Arrow*** key four times.
8. Tap ***Underline*** format button.
9. Place cursor after "s" in "this" text.
10. Hold ***Shift*** key and tap ***Left Arrow*** key four times.
11. Tap ***Underline*** format button.
12. Notice ***Underline*** format button is inactive, but text format is not removed.

***Quote***
1. Enter "this" text.
2. Place cursor after "s" in "this" text.
3. Hold ***Shift*** key and tap ***Left Arrow*** key four times.
4. Tap ***Quote*** format button.
5. Notice ***Quote*** format button is active, and text format is applied.
6. Tap ***Quote*** format button.
7. Notice ***Quote*** format button is inactive, but text format is not removed.

***List (Ordered)***
1. Enter "this" text.
2. Place cursor after "s" in "this" text.
3. Hold ***Shift*** key and tap ***Left Arrow*** key four times.
4. Tap ***List (Ordered)*** format button.
5. Notice ***List (Ordered)*** format button is active, and text format is applied.
6. Tap ***List (Ordered)*** format button.
7. Notice ***List (Ordered)*** format button is inactive, but text format is not removed.

***List (Unordered)***
1. Enter "this" text.
2. Place cursor after "s" in "this" text.
3. Hold ***Shift*** key and tap ***Left Arrow*** key four times.
4. Tap ***List (Unordered)*** format button.
5. Notice ***List (Unordered)*** format button is active, and text format is applied.
6. Tap ***List (Unordered)*** format button.
7. Notice ***List (Unordered)*** format button is inactive, but text format is not removed.

#### Tested
Google Pixel on Android 7.1.2 with AztecDemo 1.0

**Comment by khaykov** [comment] 2017-07-05 15:53
I can't reproduce this one anymore. Looks like it has been fixed, so closing for now.

**Closed by khaykov** 2017-07-05 15:53 UTC
Labels: bug
