### ISSUE TITLE
Applying redo/undo scrolls the editor to the top

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/AztecEditor-Android#275] opened 2017-02-27 22:29 UTC
### Expected

After applying undo/redo the text scroll position should stay the same as before.

### Observed

The text is scrolled all the way to the top, which might make the applied changes invisible if they're at the bottom.

**Comment by theck13** [comment] 2017-03-02 16:36
What device/emulator, API, and app are testing?  I wasn't able to reproduce this with the demonstration app on API 25, 23, or 19.  This should have been fixed with https://github.com/wordpress-mobile/WordPress-Aztec-Android/pull/110.

#### Note
I did notice the cursor remains at the final location when using ***Redo***.  I'm not sure if that's a bug or feature though.  Follow these steps to see an example.
1. Type "test" in the demonstration app.
2. Tap ***Undo*** twice.
3. Notice cursor is after "e" as expected.
4. Tap ***Redo*** twice.
5. Notice cursor remains after "e" rather than the end.

**Comment by 0nko** [comment] 2017-03-13 11:41
I was testing it on API 25. I just noticed the behavior is different now.. Try this:

1. With empty editor, type some word on the first line
2. Press enter and type something on the 2nd line
3. Go back to the 1st line and type something
4. Press undo
5. Notice the cursor jumping to the line below and how it keeps moving with undo being applied

**Comment by theck13** [comment] 2017-05-12 03:24
I'm closing this since the original issue was resolved in https://github.com/wordpress-mobile/AztecEditor-Android/pull/110.

**Closed by theck13** 2017-05-12 03:24 UTC
Labels: bug, medium priority
