### ISSUE TITLE
Missing space 

### ISSUE THREAD

**Issue by liufsd** [wordpress-mobile/AztecEditor-Android#515] opened 2017-11-03 15:05 UTC
test :
```a            nn   ccc   899999```

it will only show : 
```a nn ccc 899999```

it will missing whitespaces by '  builder.append(parser.fromHtml(cleanSource, context))'

**Comment by maxme** [comment] 2017-12-06 11:10
Can you give us more details? I'm not sure to understand what's the issue?

**Comment by maxme** [comment] 2017-12-06 14:26
This is actually a duplicate of https://github.com/wordpress-mobile/AztecEditor-Android/issues/338

**Closed by maxme** 2017-12-06 14:26 UTC
Labels: question
