### ISSUE TITLE
Crash report: RuntimeException in AztecText.toPlainHtml

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/AztecEditor-Android#452] opened 2017-08-07 22:38 UTC
There aren't a _ton_ of users effected so I've marked it medium priority.

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=2621; index=2621
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:912)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:917)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:917)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:917)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:917)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:878)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:878)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:878)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:917)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:878)
       at android.text.SpannableStringBuilder.getSpansRec(SpannableStringBuilder.java:917)
       at android.text.SpannableStringBuilder.getSpans(SpannableStringBuilder.java:826)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:76)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:49)
       at org.wordpress.aztec.AztecText.toPlainHtml(AztecText.kt:800)
       at org.wordpress.aztec.AztecText.toHtml(AztecText.kt:786)
       at org.wordpress.android.editor.AztecEditorFragment.getContent(AztecEditorFragment.java:570)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostObject(EditPostActivity.java:900)
       at org.wordpress.android.ui.posts.EditPostActivity.access$1000(EditPostActivity.java:149)
       at org.wordpress.android.ui.posts.EditPostActivity$5.run(EditPostActivity.java:916)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by khaykov** [comment] 2017-08-08 07:00
This is caused by a bug in 6.0 and 6.1, and was fixed on android side [here](https://github.com/android/platform_frameworks_base/commit/3a789f657b98fe82bf8febb3a0be9f6d616ce81d)

Wonder is we can avoid using SpannableStringBuilder in `toPlainHtml()`

**Comment by 0nko** [comment] 2017-09-29 10:40
There are some method calls there that expect an `Editable` and I'm not aware of any other direct subclass. We are using `SpannableStringBuilder` all over the place so unfortunately, I don't think we can easily replace it.

**Comment by maxme** [comment] 2017-12-06 12:12
We should add more logs to this issue so we could eventually reproduce and fix it.

**Comment by daniloercoli** [comment] 2017-12-12 17:15
Logging added in #571. Waiting next release to have some data and replicate the issue.

**Closed** 2018-06-06 10:48 UTC
Labels: bug, high priority
